language: node_js
sudo: true
install:
  - projectdir="$PWD"
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip curl
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh
  - source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install -qq mono-complete ca-certificates-mono
  - dnvm upgrade -r mono
  - cd "$projectdir"
script:
  - ./build.sh
