language: node_js
sudo: true
install:
  - projectdir="$PWD"
  - sudo apt-get update -qq
  - sudo apt-get install -qq unzip curl
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=dev sh
  - source ~/.dnx/dnvm/dnvm.sh
  - sudo apt-get install -qq gettext libssl-dev libcurl3-dev zlib1g libicu-dev # libunwind8
  - dnvm upgrade -r coreclr
  - cd "$projectdir"
script:
  - ./build.sh
