FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# IntranetGJAK

A simple file repository

## File API [/api/files]

### List All Files [GET]

You get a file listing

+ Response 200 (application/json)

        {
           "files":[
              {
                 "name":"picture1.jpg",
                 "size":902604,
                 "url":"http:\/\/example.org\/files\/picture1.jpg",
                 "thumbnailUrl":"http:\/\/example.org\/files\/thumbnail\/picture1.jpg",
                 "deleteUrl":"http:\/\/example.org\/files\/picture1.jpg",
                 "deleteType":"DELETE"
              },
              {
                 "name":"picture2.jpg",
                 "size":841946,
                 "url":"http:\/\/example.org\/files\/picture2.jpg",
                 "thumbnailUrl":"http:\/\/example.org\/files\/thumbnail\/picture2.jpg",
                 "deleteUrl":"http:\/\/example.org\/files\/picture2.jpg",
                 "deleteType":"DELETE"
              }
           ]
        }
        
        
### Download a file [GET /api/files/{id}]

You get a file

+ Response 200 (application/octet-stream)

### Upload a File [POST]

Upload any number of files in a for. You get a partial file listing.

+ Request (application/octet-stream)

+ Response 201 (application/json)

    + Body

            {
               "files":[
                  {
                     "name":"picture1.jpg",
                     "size":902604,
                     "url":"http:\/\/example.org\/files\/picture1.jpg",
                     "thumbnailUrl":"http:\/\/example.org\/files\/thumbnail\/picture1.jpg",
                     "deleteUrl":"http:\/\/example.org\/files\/picture1.jpg",
                     "deleteType":"DELETE"
                  },
                  {
                     "name":"picture2.jpg",
                     "size":841946,
                     "url":"http:\/\/example.org\/files\/picture2.jpg",
                     "thumbnailUrl":"http:\/\/example.org\/files\/thumbnail\/picture2.jpg",
                     "deleteUrl":"http:\/\/example.org\/files\/picture2.jpg",
                     "deleteType":"DELETE"
                  }
               ]
            }
