branches:
  except:
  - gh-pages
os: Visual Studio 2015
shallow_clone: true
init:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm upgrade -r clr
- cmd: dnvm upgrade -r coreclr
build_script:
- ps: .\build.ps1
cache:
 - IntranetGJAK\wwwroot\lib
 - IntranetGJAK\node_modules
 - '%APPDATA%\npm-cache'
 - '%USERPROFILE%\.dnx\packages'
 - '%USERPROFILE%\.dnx\runtimes'
